# Generated by Django 5.0.1 on 2024-02-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_petz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='image', upload_to='Our_services_about')),
                ('to_do', models.CharField(help_text='qilayotgan ish', max_length=50)),
                ('about_petz', models.CharField(help_text='hayvon haqida malumot', max_length=100)),
            ],
            options={
                'verbose_name': 'About_petz',
                'verbose_name_plural': 'About_petzs',
            },
        ),
        migrations.CreateModel(
            name='Our_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=100)),
                ('sub_title', models.CharField(help_text='sub_title', max_length=255)),
                ('helping', models.CharField(blank=True, help_text='helping', max_length=100)),
                ('photo', models.ImageField(help_text='photo', upload_to='our_services/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Our_service',
                'verbose_name_plural': 'Our_services',
            },
        ),
    ]
