# Generated by Django 5.0.1 on 2024-02-16 13:42

import django.utils.timezone
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_service',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
