# Generated by Django 5.0.1 on 2024-01-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='text', max_length=50)),
            ],
            options={
                'verbose_name': 'About_us',
                'verbose_name_plural': 'Abouts_us',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(help_text='name', max_length=30)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(help_text='image', upload_to='Blog/%Y/%m/%d')),
                ('photo_title', models.CharField(help_text='photo_title', max_length=100)),
                ('photo_sub_title', models.CharField(help_text='photo_sub_title', max_length=255)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Lates_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(help_text='photo', upload_to='blog/%Y/%m/%d')),
                ('news', models.CharField(help_text='messege', max_length=30)),
            ],
            options={
                'verbose_name': 'Lates_post',
                'verbose_name_plural': 'Lates_posts',
            },
        ),
    ]
