# Generated by Django 5.0.1 on 2024-02-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_lates_posts_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=1, help_text='author', max_length=30),
            preserve_default=False,
        ),
    ]
