# Generated by Django 5.0.1 on 2024-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_author_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_us',
        ),
        migrations.DeleteModel(
            name='Lates_posts',
        ),
        migrations.AddField(
            model_name='blog',
            name='lates_photo',
            field=models.ImageField(default=1, help_text='photo', upload_to='blog/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='news',
            field=models.CharField(default=1, help_text='messege', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.CharField(default=1, help_text='text', max_length=50),
            preserve_default=False,
        ),
    ]
