# Generated by Django 5.0.1 on 2024-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_about_us_delete_lates_posts_blog_lates_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lates_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.CharField(blank=True, help_text='messege', max_length=100)),
                ('lates_photo', models.ImageField(blank=True, help_text='photo', upload_to='blog/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='lates_photo',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='news',
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.CharField(blank=True, help_text='text', max_length=50),
        ),
    ]
