# Generated by Django 3.2.12 on 2024-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='messege', max_length=150)),
                ('sub_title', models.TextField(help_text='sub_title', max_length=300)),
                ('photo', models.ImageField(help_text='photo', upload_to='about/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Help_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='logo', upload_to='about/help_service/%Y/%m/%d')),
                ('logo_title', models.CharField(help_text='logo_title', max_length=50)),
                ('logo_sub_title', models.CharField(help_text='logo_sub_title', max_length=255)),
            ],
            options={
                'verbose_name': 'Help_service',
                'verbose_name_plural': 'Help_services',
            },
        ),
    ]
