# Generated by Django 3.2.12 on 2024-02-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Help_service',
        ),
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(default=1, help_text='logo', upload_to='about/help_service/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='logo_sub_title',
            field=models.CharField(default=1, help_text='logo_sub_title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='logo_title',
            field=models.CharField(default=1, help_text='logo_title', max_length=50),
            preserve_default=False,
        ),
    ]
