# Generated by Django 5.0.1 on 2024-02-16 13:42

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20240202_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,  default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
