# Generated by Django 5.0.1 on 2024-02-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(help_text='author', max_length=200)),
                ('job', models.CharField(help_text='job', max_length=200)),
                ('image', models.ImageField(help_text='author_photo', upload_to='Our_team/%Y/%m/%d')),
                ('author_about', models.CharField(help_text='author_about', max_length=255)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Our_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='title', max_length=255)),
                ('sub_title', models.CharField(help_text='sub_title', max_length=255)),
                ('author', models.ForeignKey(help_text='author', on_delete=django.db.models.deletion.RESTRICT, to='our_team.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
