# Generated by Django 5.0.1 on 2024-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='photo', upload_to='adoption/%Y/%m/%d')),
                ('title', models.CharField(blank=True, help_text='title', max_length=50)),
                ('sub_title', models.TextField(blank=True, help_text='sub_title')),
                ('about_title', models.CharField(blank=True, max_length=100, verbose_name='about_title')),
                ('about_sub_title', models.CharField(blank=True, help_text='about_sub_title', max_length=100)),
            ],
            options={
                'verbose_name': 'Adoption',
                'verbose_name_plural': 'Adoptions',
            },
        ),
        migrations.CreateModel(
            name='Adoption_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petz_img', models.ImageField(help_text='petz_image', upload_to='petz_image/%Y/%m/%d')),
                ('petz_name', models.CharField(help_text='petz_name', max_length=30)),
                ('petz_news', models.CharField(help_text='petz_news', max_length=200)),
            ],
            options={
                'verbose_name': 'Adoption_name',
                'verbose_name_plural': 'Adoption_names',
            },
        ),
    ]
