# Generated by Django 5.0.1 on 2024-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='petz_name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Petz_name',
        ),
    ]
