# Generated by Django 3.2.12 on 2024-02-13 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_adoption_name_remove_adoption_petz_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='petz_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adoption.adoption_name'),
            preserve_default=False,
        ),
    ]
