# Generated by Django 5.0.1 on 2024-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_auto_20240213_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petz_img', models.ImageField(help_text='petz_image', upload_to='petz_image/%Y/%m/%d')),
                ('petz_name', models.CharField(help_text='petz_name', max_length=30)),
                ('petz_news', models.CharField(help_text='petz_news', max_length=200)),
            ],
            options={
                'verbose_name': 'Adoption_name',
                'verbose_name_plural': 'Adoption_names',
            },
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='petz_img',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='petz_name',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='petz_news',
        ),
    ]
